name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        include:
          - os: macos-latest
            commandTest: ./solipath gradle build
            commandAcceptLicenses: (while sleep 3; do echo "y"; done) | ./solipath sdkmanager --licenses
            commandInstrumentedTest: ./solipath gradle pixel2api30DebugAndroidTest
          - os: ubuntu-latest
            commandTest: ./solipath gradle build
            commandAcceptLicenses: yes | ./solipath sdkmanager --licenses
            commandInstrumentedTest: ./solipath gradle pixel2api30DebugAndroidTest
          - os: windows-latest
            commandTest: .\solipath gradle build
            commandAcceptLicenses: yes | .\solipath sdkmanager.bat --licenses
            commandInstrumentedTest: .\solipath gradle pixel2api30DebugAndroidTest
    steps:
      - uses: actions/checkout@v2
      - name: run gradle build to identify licenses
        run: ${{matrix.commandTest}}
      - name: accept licenses
        run: ${{matrix.commandAcceptLicenses}}
      - name: run gradle build
        run: ${{matrix.commandTest}}
      - name: Run instrumented tests
        run: ${{matrix.commandInstrumentedTest}}
