name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        include:
          - os: macos-latest
            commandTest: unset ANDROID_SDK_ROOT && ./solipath gradle build
            commandAcceptLicenses: unset ANDROID_SDK_ROOT && ./solipath sdkmanager --licenses || true
            commandInstrumentedTest: unset ANDROID_SDK_ROOT && ./solipath gradle pixel2api30DebugAndroidTest
          - os: ubuntu-latest
            commandTest: unset ANDROID_SDK_ROOT && ./solipath gradle build
            commandAcceptLicenses: unset ANDROID_SDK_ROOT && yes | ./solipath sdkmanager --licenses || true
            commandInstrumentedTest: unset ANDROID_SDK_ROOT && ./solipath gradle pixel2api30DebugAndroidTest
          - os: windows-latest
            commandTest: setx ANDROID_SDK_ROOT="" && .\solipath gradle build
            commandAcceptLicenses: setx ANDROID_SDK_ROOT="" && .\solipath sdkmanager --licenses
            commandInstrumentedTest: setx ANDROID_SDK_ROOT="" && .\solipath gradle pixel2api30DebugAndroidTest
    steps:
      - uses: actions/checkout@v2
      - name: run gradle build to identify licenses
        run: ${{matrix.commandTest}}
      - name: accept licenses
        run: ${{matrix.commandAcceptLicenses}}
      - name: run gradle build
        run: ${{matrix.commandTest}}
      - name: Run instrumented tests
        run: ${{matrix.commandInstrumentedTest}}
