name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        include:
          - os: macos-latest
            commandTest: unset ANDROID_SDK_ROOT && ./solipath gradle build
            commandInstrumentedTest: unset ANDROID_SDK_ROOT && ./solipath gradle pixel2api30DebugAndroidTest
          - os: ubuntu-latest
            commandTest: unset ANDROID_SDK_ROOT && ./solipath gradle build
            commandInstrumentedTest: unset ANDROID_SDK_ROOT && ./solipath gradle pixel2api30DebugAndroidTest
          - os: windows-latest
            commandTest: set ANDROID_SDK_ROOT= && .\solipath gradle build
            commandInstrumentedTest: set ANDROID_SDK_ROOT= && .\solipath gradle pixel2api30DebugAndroidTest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ${{matrix.commandTest}}
      - name: Run instrumented tests
        run: ${{matrix.commandInstrumentedTest}}
